### ISSUE TITLE
GoodFriend game crash

### ISSUE THREAD

**Issue by Hapseleg** [Blooym/GoodFriend#168]
Hey just wanted to report a game crash, went down instantly, no dalamud error message or anything

```
2024-03-08 17:32:05.978 +01:00 [ERR] [GoodFriend] <PlayerEventStreamModule::OnPlayerStreamException>: Exception received from event stream: System.Net.Http.HttpProtocolException: The HTTP/2 server reset the stream. HTTP/2 error code 'INTERNAL_ERROR' (0x2).
   at System.Net.Http.Http2Connection.ThrowRequestAborted(Exception innerException)
   at System.Net.Http.Http2Connection.Http2Stream.CheckResponseBodyState()
   at System.Net.Http.Http2Connection.Http2Stream.TryReadFromBuffer(Span`1 buffer, Boolean partOfSyncRead)
   at System.Net.Http.Http2Connection.Http2Stream.ReadData(Span`1 buffer, HttpResponseMessage responseMessage)
   at System.Net.Http.HttpBaseStream.Read(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.StreamReader.ReadBuffer()
   at System.IO.StreamReader.get_EndOfStream()
   at GoodFriend.Client.Http.SseClient`1.Connect() in /work/repo/src/Client/Http/SseClient.cs:line 209
2024-03-08 17:32:05.978 +01:00 [ERR] [GoodFriend] <AnnouncementStreamModule::OnAnnouncementStreamException>: Exception received from event stream: System.Net.Http.HttpProtocolException: The HTTP/2 server reset the stream. HTTP/2 error code 'INTERNAL_ERROR' (0x2).
   at System.Net.Http.Http2Connection.ThrowRequestAborted(Exception innerException)
   at System.Net.Http.Http2Connection.Http2Stream.CheckResponseBodyState()
   at System.Net.Http.Http2Connection.Http2Stream.TryReadFromBuffer(Span`1 buffer, Boolean partOfSyncRead)
   at System.Net.Http.Http2Connection.Http2Stream.ReadData(Span`1 buffer, HttpResponseMessage responseMessage)
   at System.Net.Http.HttpBaseStream.Read(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.StreamReader.ReadBuffer()
   at System.IO.StreamReader.get_EndOfStream()
   at GoodFriend.Client.Http.SseClient`1.Connect() in /work/repo/src/Client/Http/SseClient.cs:line 209
```

Thanks for all your work, its a nice plugin :3 <3

**Comment by Blooym** [comment]
That's really strange. I was doing some server work earlier today that likely caused the connection issue but it should never be able to cause a crash or anything. Was this the last entry in your dalamud.log?

**Comment by Hapseleg** [comment]
Yes this was the last entry and if I search for "[ERR] [GoodFriend]" I can see I've had 16 errors, here are the rest:

```
2024-03-08 17:39:45.550 +01:00 [ERR] [GoodFriend] <AnnouncementStreamModule::OnAnnouncementStreamException>: Exception received from event stream: System.Net.Http.HttpProtocolException: The HTTP/2 server reset the stream. HTTP/2 error code 'INTERNAL_ERROR' (0x2).
   at System.Net.Http.Http2Connection.ThrowRequestAborted(Exception innerException)
   at System.Net.Http.Http2Connection.Http2Stream.CheckResponseBodyState()
   at System.Net.Http.Http2Connection.Http2Stream.TryReadFromBuffer(Span`1 buffer, Boolean partOfSyncRead)
   at System.Net.Http.Http2Connection.Http2Stream.ReadData(Span`1 buffer, HttpResponseMessage responseMessage)
   at System.Net.Http.HttpBaseStream.Read(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.StreamReader.ReadBuffer()
   at System.IO.StreamReader.get_EndOfStream()
   at GoodFriend.Client.Http.SseClient`1.Connect() in /work/repo/src/Client/Http/SseClient.cs:line 209
2024-03-08 17:39:45.553 +01:00 [ERR] [GoodFriend] <PlayerEventStreamModule::OnPlayerStreamException>: Exception received from event stream: System.Net.Http.HttpProtocolException: The HTTP/2 server reset the stream. HTTP/2 error code 'INTERNAL_ERROR' (0x2).
   at System.Net.Http.Http2Connection.ThrowRequestAborted(Exception innerException)
   at System.Net.Http.Http2Connection.Http2Stream.CheckResponseBodyState()
   at System.Net.Http.Http2Connection.Http2Stream.TryReadFromBuffer(Span`1 buffer, Boolean partOfSyncRead)
   at System.Net.Http.Http2Connection.Http2Stream.ReadData(Span`1 buffer, HttpResponseMessage responseMessage)
   at System.Net.Http.HttpBaseStream.Read(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.StreamReader.ReadBuffer()
   at System.IO.StreamReader.get_EndOfStream()
   at GoodFriend.Client.Http.SseClient`1.Connect() in /work/repo/src/Client/Http/SseClient.cs:line 209
   
```
```
2024-03-08 17:40:15.654 +01:00 [ERR] [GoodFriend] <PlayerEventStreamModule::OnPlayerStreamException>: Exception received from event stream: System.Net.Http.HttpRequestException: Response status code does not indicate success: 521 ().
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at System.Net.Http.HttpClient.GetStreamAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   at GoodFriend.Client.Http.SseClient`1.Connect() in /work/repo/src/Client/Http/SseClient.cs:line 202
2024-03-08 17:40:16.644 +01:00 [ERR] [GoodFriend] <AnnouncementStreamModule::OnAnnouncementStreamException>: Exception received from event stream: System.Net.Http.HttpRequestException: Response status code does not indicate success: 521 ().
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at System.Net.Http.HttpClient.GetStreamAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   at GoodFriend.Client.Http.SseClient`1.Connect() in /work/repo/src/Client/Http/SseClient.cs:line 202
```
   
```
2024-03-08 17:40:45.600 +01:00 [ERR] [GoodFriend] <AnnouncementStreamModule::OnAnnouncementStreamException>: Exception received from event stream: System.Net.Http.HttpRequestException: Response status code does not indicate success: 521 ().
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at System.Net.Http.HttpClient.GetStreamAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   at GoodFriend.Client.Http.SseClient`1.Connect() in /work/repo/src/Client/Http/SseClient.cs:line 202
2024-03-08 17:40:45.601 +01:00 [ERR] [GoodFriend] <PlayerEventStreamModule::OnPlayerStreamException>: Exception received from event stream: System.Net.Http.HttpRequestException: Response status code does not indicate success: 521 ().
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at System.Net.Http.HttpClient.GetStreamAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   at GoodFriend.Client.Http.SseClient`1.Connect() in /work/repo/src/Client/Http/SseClient.cs:line 202
2024-03-08 17:40:46.500 +01:00 [DBG] [InventoryTools] 1709916046500 Itemodr reparsed
2024-03-08 17:40:46.500 +01:00 [DBG] [InventorySearchBar] 1709916046500 Itemodr reparsed
2024-03-08 17:41:12.953 +01:00 [DBG] [InventoryTools] Overlays refreshing, active filter is no filter
2024-03-08 17:41:15.606 +01:00 [ERR] [GoodFriend] <PlayerEventStreamModule::OnPlayerStreamException>: Exception received from event stream: System.Net.Http.HttpRequestException: Response status code does not indicate success: 521 ().
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at System.Net.Http.HttpClient.GetStreamAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   at GoodFriend.Client.Http.SseClient`1.Connect() in /work/repo/src/Client/Http/SseClient.cs:line 202
2024-03-08 17:41:15.610 +01:00 [ERR] [GoodFriend] <AnnouncementStreamModule::OnAnnouncementStreamException>: Exception received from event stream: System.Net.Http.HttpRequestException: Response status code does not indicate success: 521 ().
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at System.Net.Http.HttpClient.GetStreamAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   at GoodFriend.Client.Http.SseClient`1.Connect() in /work/repo/src/Client/Http/SseClient.cs:line 202
```
   
```
System.Net.Http.HttpRequestException: Response status code does not indicate success: 521 ().
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at System.Net.Http.HttpClient.GetStreamAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   at GoodFriend.Client.Http.SseClient`1.Connect() in /work/repo/src/Client/Http/SseClient.cs:line 202
2024-03-08 17:41:45.610 +01:00 [ERR] [GoodFriend] <AnnouncementStreamModule::OnAnnouncementStreamException>: Exception received from event stream: System.Net.Http.HttpRequestException: Response status code does not indicate success: 521 ().
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at System.Net.Http.HttpClient.GetStreamAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   at GoodFriend.Client.Http.SseClient`1.Connect() in /work/repo/src/Client/Http/SseClient.cs:line 202
2024-03-08 17:41:52.199 +01:00 [DBG] [Penumbra] Creating temporary collection Ma... (-138).

System.Net.Http.HttpRequestException: Response status code does not indicate success: 521 ().
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at System.Net.Http.HttpClient.GetStreamAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   at GoodFriend.Client.Http.SseClient`1.Connect() in /work/repo/src/Client/Http/SseClient.cs:line 202
2024-03-08 17:42:15.604 +01:00 [ERR] [GoodFriend] <PlayerEventStreamModule::OnPlayerStreamException>: Exception received from event stream: System.Net.Http.HttpRequestException: Response status code does not indicate success: 521 ().
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at System.Net.Http.HttpClient.GetStreamAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   at GoodFriend.Client.Http.SseClient`1.Connect() in /work/repo/src/Client/Http/SseClient.cs:line 202
```

**Comment by Blooym** [comment]
The server itself was down for a little bit of today due to me having to move services around which explains the 522/HTTP resets in the log file. 

What I don't understand is how it caused a crash - these error messages are written after a connection error has been safely handled, it's really strange

**Comment by Hapseleg** [comment]
Yeah it would be pretty odd, maybe it was something else but it just happened at that exact moment I got the error or something ^^

**Comment by Blooym** [comment]
I'll take a look and double check anyways :)

**Comment by Blooym** [comment]
Haven't been able to find a cause or replicate, I am going to consider this resolved for now. Let me know if you run into a crash with GoodFriend again and I'll reopen and investigate :)
